/*
 * @Description: 左侧菜单
 * @Author: xiaoben(xiaoben0527@qq.com)
 */
/**
 *id          主键
 *parentId    父id 0:顶级
 *sort        排序,越小越靠前
 *name        名称 要唯一
 *path        路径
 *component   页面地址
 *redirect    重定向
 *hidden      是否隐藏 1:隐藏 0:显示
 *alwaysShow  一直显示根路由1:是 0:否
 *title       菜单栏的名字
 *icon        图标
 *noCache     不缓存 1是 0否
 *breadcrumb  是否在面包屑中显示 1是 0否
 *affix       固定在tags标签栏中(不可删除) 1是 0否
 *noTags      不在tags标签栏中显示 1是 0否
 *open        展开当前子菜单(如果有子菜单)
 *activeMenu  高亮菜单
 *created_at  创建时间
 *updated_at  修改时间
 */
export default [
  {
    activeMenu: '',
    affix: 0,
    alwaysShow: 1,
    breadcrumb: 1,
    component: '#',
    createdAt: 1656645149,
    hidden: 0,
    icon: 'Setting',
    id: 2,
    name: 'System',
    noCache: 0,
    noTags: 0,
    open: 0,
    parentId: 0,
    path: '/system',
    redirect: '/system/index',
    roles: ['admin'],
    sort: 1,
    title: '系统配置',
    updatedAt: 1686560474
  },
  {
    activeMenu: '',
    affix: 0,
    alwaysShow: 0,
    breadcrumb: 1,
    component: 'system/index',
    createdAt: 1656645192,
    hidden: 0,
    icon: '',
    id: 3,
    name: 'SystemIndex',
    noCache: 0,
    noTags: 0,
    open: 0,
    parentId: 2,
    path: 'index',
    redirect: '',
    roles: ['admin'],
    sort: 1,
    title: '系统配置',
    updatedAt: 1686560480
  },
  {
    activeMenu: '',
    affix: 0,
    alwaysShow: 0,
    breadcrumb: 1,
    component: 'role/index',
    createdAt: 0,
    hidden: 0,
    icon: '',
    id: 5,
    name: 'RoleIndex',
    noCache: 0,
    noTags: 0,
    open: 0,
    parentId: 4,
    path: 'index',
    redirect: '',
    roles: ['admin'],
    sort: 1,
    title: '角色',
    updatedAt: 1687228407
  },
  {
    activeMenu: '/role/index',
    affix: 0,
    alwaysShow: 1,
    breadcrumb: 1,
    component: 'role/edit',
    createdAt: 1687231150,
    hidden: 1,
    icon: '',
    id: 20,
    name: 'RoleAdd',
    noCache: 0,
    noTags: 0,
    open: 0,
    parentId: 4,
    path: 'roleAdd/:id',
    redirect: '',
    roles: ['admin'],
    sort: 2,
    title: '添加角色',
    updatedAt: 0
  },
  {
    activeMenu: '/role/index',
    affix: 0,
    alwaysShow: 0,
    breadcrumb: 1,
    component: 'role/edit',
    createdAt: 0,
    hidden: 1,
    icon: '',
    id: 6,
    name: 'RoleEdit',
    noCache: 0,
    noTags: 0,
    open: 0,
    parentId: 4,
    path: 'roleEdit/:id',
    redirect: '',
    roles: ['admin'],
    sort: 3,
    title: '编辑角色',
    updatedAt: 1687231164
  },
  {
    activeMenu: '',
    affix: 0,
    alwaysShow: 0,
    breadcrumb: 1,
    component: 'role/account',
    createdAt: 0,
    hidden: 0,
    icon: '',
    id: 7,
    name: 'RoleAccount',
    noCache: 0,
    noTags: 0,
    open: 0,
    parentId: 4,
    path: 'account',
    redirect: '',
    roles: ['admin'],
    sort: 4,
    title: '账号列表',
    updatedAt: 1687228425
  },
  {
    activeMenu: '/role/account',
    affix: 0,
    alwaysShow: 1,
    breadcrumb: 1,
    component: 'role/accountEdit',
    createdAt: 1687228349,
    hidden: 1,
    icon: '',
    id: 18,
    name: 'RoleAccountAdd',
    noCache: 0,
    noTags: 0,
    open: 0,
    parentId: 4,
    path: 'accountAdd/:id',
    redirect: '',
    roles: ['admin'],
    sort: 5,
    title: '添加账号',
    updatedAt: 1687228519
  },
  {
    activeMenu: '',
    affix: 0,
    alwaysShow: 1,
    breadcrumb: 1,
    component: '#',
    createdAt: 0,
    hidden: 0,
    icon: 'Connection',
    id: 4,
    name: 'Role',
    noCache: 0,
    noTags: 0,
    open: 0,
    parentId: 0,
    path: '/role',
    redirect: '/role/index',
    roles: ['admin'],
    sort: 6,
    title: '账号管理',
    updatedAt: 0
  },
  {
    activeMenu: '/role/account',
    affix: 0,
    alwaysShow: 1,
    breadcrumb: 1,
    component: 'role/accountEdit',
    createdAt: 1687228506,
    hidden: 1,
    icon: '',
    id: 19,
    name: 'RoleAccountEdit',
    noCache: 0,
    noTags: 0,
    open: 0,
    parentId: 4,
    path: 'accountEdit/:id',
    redirect: '',
    roles: ['admin'],
    sort: 6,
    title: '编辑账号',
    updatedAt: 0
  },
  {
    activeMenu: '',
    affix: 0,
    alwaysShow: 1,
    breadcrumb: 1,
    component: '#',
    createdAt: 0,
    hidden: 0,
    icon: 'SetUp',
    id: 8,
    name: 'Setpassword',
    noCache: 0,
    noTags: 0,
    open: 0,
    parentId: 0,
    path: '/setpassword',
    redirect: '/setpassword/index',
    roles: ['admin'],
    sort: 7,
    title: '修改密码',
    updatedAt: 0
  },
  {
    activeMenu: '',
    affix: 0,
    alwaysShow: 1,
    breadcrumb: 1,
    component: '#',
    createdAt: 0,
    hidden: 0,
    icon: 'Document',
    id: 14,
    name: 'AdminLog',
    noCache: 0,
    noTags: 0,
    open: 0,
    parentId: 0,
    path: '/adminLog',
    redirect: '/adminLog/index',
    roles: ['admin'],
    sort: 9,
    title: '操作日志',
    updatedAt: 0
  },
  {
    activeMenu: '',
    affix: 0,
    alwaysShow: 0,
    breadcrumb: 1,
    component: 'setpassword/index',
    createdAt: 0,
    hidden: 0,
    icon: '',
    id: 9,
    name: 'SetpasswordIndex',
    noCache: 0,
    noTags: 0,
    open: 0,
    parentId: 8,
    path: 'index',
    redirect: '',
    roles: ['admin'],
    sort: 99,
    title: '修改密码',
    updatedAt: 0
  },
  {
    activeMenu: '',
    affix: 0,
    alwaysShow: 1,
    breadcrumb: 1,
    component: '#',
    createdAt: 0,
    hidden: 0,
    icon: 'Monitor',
    id: 10,
    name: 'Model',
    noCache: 0,
    noTags: 0,
    open: 0,
    parentId: 0,
    path: '/model',
    redirect: '/model/index',
    roles: ['admin'],
    sort: 99,
    title: '模型',
    updatedAt: 1639647537
  },
  {
    activeMenu: '',
    affix: 0,
    alwaysShow: 0,
    breadcrumb: 1,
    component: 'model/index',
    createdAt: 0,
    hidden: 0,
    icon: '',
    id: 11,
    name: 'ModelIndex',
    noCache: 0,
    noTags: 0,
    open: 0,
    parentId: 10,
    path: 'index',
    redirect: '',
    roles: ['admin'],
    sort: 99,
    title: '模型',
    updatedAt: 0
  },
  {
    activeMenu: '/model/index',
    affix: 0,
    alwaysShow: 0,
    breadcrumb: 1,
    component: 'model/edit',
    createdAt: 0,
    hidden: 1,
    icon: '',
    id: 12,
    name: 'ModelEdit',
    noCache: 0,
    noTags: 0,
    open: 0,
    parentId: 10,
    path: 'edit/:id',
    redirect: '',
    roles: ['admin'],
    sort: 99,
    title: '编辑',
    updatedAt: 0
  },
  {
    activeMenu: '',
    affix: 0,
    alwaysShow: 0,
    breadcrumb: 1,
    component: 'adminLog/index',
    createdAt: 0,
    hidden: 0,
    icon: '',
    id: 15,
    name: 'AdminLogIndex',
    noCache: 0,
    noTags: 0,
    open: 0,
    parentId: 14,
    path: 'index',
    redirect: '',
    roles: ['admin'],
    sort: 99,
    title: '操作日志',
    updatedAt: 0
  }
];
